/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ben' at '1/28/16 10:34 PM' with Gradle 2.10
 *
 * @author ben, @date 1/28/16 10:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
