CREATE SCHEMA `traverse`;
  
CREATE TABLE `traverse`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(64) NOT NULL,
  `PASSWORD_HASH` VARCHAR(128) NOT NULL,
  `PASSWORD_SALT` VARCHAR(32) NOT NULL,
  `ENABLED` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));
  
 CREATE TABLE `traverse`.`user_roles` (
  `USER_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(64) NOT NULL,
  `ROLE` varchar(64) NOT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  UNIQUE KEY `USERNAME_ROLE_UNIQUE` (`ROLE`,`USERNAME`),
  KEY `FK_USERID_IDX` (`USERNAME`),
  CONSTRAINT `FK_USERID` FOREIGN KEY (`USERNAME`) REFERENCES users (`USERNAME`));
  