CREATE SCHEMA 'traverse';

CREATE TABLE 'traverse'.'user' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'USERNAME' VARCHAR(64) NOT NULL,
  'PASSWORD_HASH' VARCHAR(128) NOT NULL,
  'PASSWORD_SALT' VARCHAR(32) NOT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'USERNAME_UNIQUE' ('USERNAME' ASC),
  UNIQUE INDEX 'ID_UNIQUE' ('⁯ID' ASC));